config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :locations, only: [:index, :show]
  resources :videos, only: [:index, :show]
  resources :articles, only: [:index, :show]
  resources :dolars, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
end

app/models/dolar.rb
class Dolar < ApplicationRecord
end

app/models/location.rb
class Location < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true, uniqueness: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/dolars_controller.rb
class DolarsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_dolars, only: [:show, :edit, :update]
  def index
    @dolars = Dolar.all
  end

  def show

  end

  def edit
  end

  def update
    @dolar.update(dolars_params)
    redirect_to dolar_path(@dolar)
  end

  private

  def dolars_params
    params.require(:dolar).permit(:dolarv, :dolarc, :euroc, :eurov, :realc, :realv)
  end

  def set_dolars
    @dolar = Dolar.find(params[:id])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  skip_before_action :authenticate_user!


  def index
    @locations = Location.order(created_at: :desc)

    @locations = Location.where.not(latitude: nil, longitude: nil)

    @markers = @locations.map do |location|
      {
        lng: location.longitude,
        lat: location.latitude,
        infoWindow: {content: render_to_string(partial: "/locations/map_box", locals: { location: location }) }

      }
    end
  end

  def show
    @location = Location.find(params[:id])
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @videos = Video.all
    if params["region"]
      @videos = Video.where(region: params["region"])
    elsif params["created_at"]
      @videos = Video.order(created_at: :desc)
    elsif params["rating"]
      @videos = Video.order(rating: :desc)
    else
      @videos
    end
  end

  def show
    @video = Video.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/index.html.erb
<div class="main-article-container">
 <div class="sidebar">
 </div>
 <div class="articles">

  <% @articles.each do |article| %>

  <%= link_to article_path(article) do %>
  <div class="article">
    <img src="<%= article.photo_1 %>" alt="">

    <div class="article-body">
     <h3><%= article.title %></h3>
     <h5><%= article.subtitle %></h5>
   </div>
 </div>
 <%end%>
 <%end%>
</div>



<div class="messages">

</div>


</div>

app/views/articles/show.html.erb
<div class="article-banner">
  <img src="<%= @article.photo_1 %>" alt="">
</div>
<div class="article-container">
  <h1><%= @article.title %></h1>
  <h5><%= @article.subtitle %></h5>
  <h6><%= @article.writer %> || <%= @article.created_at.strftime("%d de %B de %Y") %> </h6>
  <p><%=  @article.main_article%></p>
  <img src="<%= @article.photo_2 %> " alt="">
  <p> <%= @article.sub_article %></p>
  <img src="<%= @article.photo_3 %> " alt="">
</div>
<div class="article-button">
  <%= link_to 'Back to Articles', articles_path, class: 'btn btn-primary'  %>
</div>

app/views/dolars/edit.html.erb
<h1>Editar</h1>



<%= simple_form_for @dolar do |f| %>
        <%= f.error_notification %>


<%= f.input :dolarc, required: true, value: @dolar.dolarc %>
         <%= f.input :dolarv, required: true, value: @dolar.dolarv %>
          <%= f.input :euroc, required: true, value: @dolar.euroc %>
          <%= f.input :eurov, required: true, value: @dolar.eurov %>
          <%= f.input :realc, required: true, value: @dolar.realc %>
         <%= f.input :realv, required: true, value: @dolar.realv %>


<%= f.button :submit, "update", class: 'btn btn-primary' %>

<% end %>

app/views/dolars/index.html.erb
<div class="cotizacion-container">
  <% @dolars.each do |dolar| %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Moneda</th>
        <th scope="col"></th>
        <th scope="col">Venta</th>
        <th scope="col">Compra</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1554760381/flag-usa.jpg" alt=""> <br>Dolar </td>
        <td></td>
        <td><%= dolar.dolarv %></td>
        <td><%= dolar.dolarc %></td>
      </tr>
      <tr>
        <td><img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1554760381/flag-euro.jpg" alt=""><br>Euro</td>
        <td></td>
        <td><%= dolar.eurov %></td>
        <td><%= dolar.euroc %></td>
      </tr>
      <tr>
        <td><img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1554760381/flag-br.jpg" alt=""><br>Real</td>
        <td></td>
        <td><%= dolar.realv %></td>
        <td><%= dolar.realc %></td>
      </tr>
    </tbody>
  </table>
  <div class="dolar-footer">
    <p>Actualizado: <%= dolar.updated_at.strftime('%d/%m/%y - %H.%M') %>-<%= link_to 'Lamebo',dolar_path(dolar) %> </p>
  </div>
  <% end %>
</div>

app/views/dolars/show.html.erb
<h1>Cotizacion</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Moneda</th>
      <th scope="col"></th>
      <th scope="col">Venta</th>
      <th scope="col">Compra</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Dolar</td>
      <td></td>
      <td><%= @dolar.dolarv %></td>
      <td><%= @dolar.dolarc %></td>
    </tr>
    <tr>
      <td>Euro</td>
      <td></td>
      <td><%= @dolar.eurov %></td>
      <td><%= @dolar.euroc %></td>
    </tr>
    <tr>
      <td>Real</td>
      <td></td>
      <td><%= @dolar.realv %></td>
      <td><%= @dolar.realc %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit' , edit_dolar_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_pack_tag 'map' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'map' %>
  </body>
</html>

app/views/locations/_map_box.html.erb
<h1><%= location.name %></h1>
<p><%= location.address %></p>

app/views/locations/index.html.erb
<div class="main-container">
  <div
  id="map"
  style="width: 100%;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  >
  </div>
  <div class="locations">

    <% @locations.each do |location| %>
    <%= link_to location_path(location) do%>
    <div class="location-content", data-location-id="<%= location.id %>">
      <img src="<%= location.photo %>" alt="card img">
      <h3><%= location.name %></h3>
    </div>
       <%end %>
       <%end %>
  </div>



</div>

app/views/locations/show.html.erb
<div class="container">
  <div class="location-description">
    <h2> <%= @location.name %></h2>
    <img src="<%= @location.photo %>" alt="card img">
    <p> <%= @location.address %></p>
    <p> <%= @location.latitude %></p>
    <p> <%= @location.longitude %></p>
  </div>
</div>

app/views/pages/home.html.erb
  <div class="panel-wrapper">
    <div class="panel-container">
      <div class="panels">
        <div class="panel panel1">
          <p><i class="far fa-smile"></i></p>
          <p>Let's</p>
          <p>Enjoy</p>
        </div>
        <div class="panel panel2">
          <p>Always</p>
          <p>Surf</p>
          <p>Hard</p>
        </div>
        <div class="panel panel3">
          <p>Live</p>
          <p>The</p>
          <p>Present</p>
        </div>
        <div class="panel panel4">
          <p>The</p>
          <p>World</p>
          <p>It's yours</p>
        </div>
      </div>
    </div>
  </div>

  <script>
      const panels = document.querySelectorAll('.panel');
      function toggleOpen() {
        console.log('Hello');
        this.classList.toggle('open');
      }
      function toggleActive(e) {
        console.log(e.propertyName);
        if (e.propertyName.includes('flex')) {
          this.classList.toggle('open-active');
        }
      }
      panels.forEach(panel => panel.addEventListener('click', toggleOpen));
      panels.forEach(panel => panel.addEventListener('transitionend', toggleActive));
    </script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to dolars_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png", height: 50  %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <!-- Links when logged in -->
    <div class="dropdown">
      <button class="dropbtn">Articles <i class="fas fa-angle-down"></i></button>
      <div class="dropdown-content">
        <h5><%= link_to articles_path do %>Articles<% end %></h5>
        <h5><%= link_to articles_path do %>News<% end %></h5>
      </div>
    </div>
    <div class="dropdown">
      <button class="dropbtn">Gear <i class="fas fa-angle-down"></i></button>
      <div class="dropdown-content">
        <!--  -->
      </div>
    </div>
    <div class="dropdown">
      <button class="dropbtn">Videos <i class="fas fa-angle-down"></i></button>
      <div class="dropdown-content">
        <h5><%= link_to "All Videos", videos_path %> </h5>
        <h5><%= link_to videos_path(rating: :desc) do %>
         Trend<%end %></h5>
         <h5><%= link_to videos_path(created_at: :desc) do %>
           Recent<% end %></h5>
         </div>
       </div>
       <div class="dropdown">
        <button class="dropbtn">Locations <i class="fas fa-angle-down"></i></button>
        <div class="dropdown-content">
          <h5><%= link_to locations_path do %>
            Locations<% end %></h5>

          </div>
        </div>



        <!-- Avatar with dropdown menu -->
        <% if user_signed_in? %>
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <button class="dropbtn">
              <%= image_tag "logo.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %> </button>
              <div class="dropdown-content">
                <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i> <%= t(".sign_out", default: "Log out") %>
                <% end %>
              </div>
            </div>
          </div>
          <% else %>
          <!-- Login link (when logged out) -->
          <%= link_to t(".sign_in", default: "Iniciar Sesion"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <% end %>
        </div>

        <!-- Dropdown list appearing on mobile only -->
        <% if user_signed_in? %>
        <div class="navbar-wagon-item hidden-md hidden-lg">
          <div class="dropdown">
            <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li><%= link_to articles_path do %><i class="fas fa-newspaper"></i> Articles</li>
              <% end %>
              <li><%= link_to locations_path do %><i class="fas fa-mountain"></i> Locations</li>
              <% end %>
              <li><%= link_to videos_path do %><i class="fas fa-video"></i> Videos</li>
              <% end %>
              <li><%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i> <%= t(".sign_out", default: "Log out") %>
                <% end %></li>
              </ul>
            </div>
          </div>
          <% else %>
          <div class="navbar-wagon-item hidden-md hidden-lg">
            <div class="dropdown">
              <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
                <li><%= link_to t(".sign_in", default: "Iniciar Sesion"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
                <li><%= link_to articles_path do %><i class="fas fa-newspaper"></i> Articles</li>
                <% end %>

                <li><%= link_to videos_path do %><i class="fas fa-video"></i> Videos</li>
                <% end %>
              </ul>
              <% end %>
            </div>
          </div>
        </div>

app/views/videos/index.html.erb
<div class="main-video-container">
  <div id="list">
    <%= link_to videos_path do %>
     <h2><i class="fas fa-home" style="color:red"></i>Home
     </h2><%end %>
    <%= link_to videos_path(rating: :desc) do %>
     <h5><i class="fas fa-fire"></i>Trend
     </h5><%end %>
    <h5><%= link_to videos_path(created_at: :desc) do %>
      <i class="fas fa-stopwatch"></i>Recent<% end %></h5>

<h3><button id="regionButton" onClick="myRegionFunction(); toggleMarcaText(this.id);">Region -</button></h3>
  <div id = "marcasDiv">

    <%= link_to videos_path(region: "Usa") do %><h5>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;United States</h5><% end %>
    <%= link_to videos_path(region: "France") do %><h5>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;France</h5><% end %>
    <%= link_to videos_path(region: "Canada") do %><h5>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Canada</h5><% end %>
    <%= link_to videos_path(region: "Japan") do %><h5>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Japan</h5><% end %>
    <div style="display:none;" id="myDIV">
       <%= link_to videos_path(region: "Austria") do %><h5>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Austria</h5><% end %>
       <%= link_to videos_path(region: "Argentina") do %><h5>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Argentina</h5><% end %>
       <%= link_to videos_path(region: "Italy") do %><h5>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Italy</h5><% end %>
       <%= link_to videos_path(region: "New Zeland") do %><h5>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;New Zeland</h5>
       <%= link_to videos_path(region: "Suiza") do %><h5>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Switzerland</h5><% end %>
    </div><% end %>
      <button id="myButton" onClick="myFunction(); toggleText(this.id);">+ More</button>
  </div>

 <script>
           function myRegionFunction() {
            let b = document.getElementById("marcasDiv");
            if (b.style.display === "none")
            {
              b.style.display = "block";
            } else {
              b.style.display = "none";
            }
           }
           function toggleMarcaText(marcaButton) {
            if (document.getElementById(marcaButton).innerText == "Region -")
             {
                 document.getElementById(marcaButton).innerText = "Region +";
             }
             else
             {
               document.getElementById(marcaButton).innerText = "Region -";
             }
           }
            function myFunction() {
            var x = document.getElementById("myDIV");
            if (x.style.display === "none") {
              x.style.display = "block";
            } else {
              x.style.display = "none";
            }
          }
            function toggleText(button_id)  {
             if (document.getElementById(button_id).innerText == "+ More")
             {
                 document.getElementById(button_id).innerText = "- Less";
             }
             else
             {
               document.getElementById(button_id).innerText = "+ More";
             }
          }
        </script>

     <h6> Library</h6>

     <h5><%= link_to videos_path do %>
     <i class="fas fa-clock"></i> See Later
     <%end %></h5>
     <h5><%= link_to videos_path do %>
     <i class="fas fa-heart"></i> Favorites
     <%end %></h5>


  </div>

  <div class="video-container">
    <div class="row" id="video-index">
      <% @videos.each do |video|  %>
      <div class="col-xs-12 col-sm-4 col-md-2">
        <%= link_to video_path(video) do %>
        <div class="card" style="width: 210px;">
          <img class="card-img-top" src="https://img.youtube.com/vi/<%= video.url %>/hqdefault.jpg" alt="Card image cap">
          <div class="card-body">
            <h5><%= video.title %></h5>
            <p><%= video.region %> </p>
            <p> <%= video.created_at.strftime("%d de %B de %Y") %></p>
            <p> <i class="fas fa-thumbs-up"></i>(23) <i class="fas fa-thumbs-down"></i>(3)</p>
          </div>
        </div>
        <%end %>
      </div>
      <%end %>
    </div>
  </div>
</div>

app/views/videos/show.html.erb
<div class="video-container">
  <div class="video-wrapper">

    <div class="video-player">
      <iframe width= "840" height= "540" src="https://www.youtube.com/embed/<%= @video.url %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <h5><%= @video.title %></h5>
      <h5><%= @video.region %></h5>
      <h5><%= @video.rating %></h5>
    </div>
  </div>
  <div class="video-button">
  <%= link_to 'Back to Videos' ,videos_path, class: 'btn btn-primary' %>
</div>
</div>